[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m~/PY/Gen/catalan_conjecture.py[0m in [0;36m<module>[0;34m[0m
[1;32m     27[0m [0;34m[0m[0m
[1;32m     28[0m [0;32mif[0m [0m__name__[0m [0;34m==[0m [0;34m"__main__"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 29[0;31m     [0mcatalan1[0m[0;34m([0m[0mx[0m[0;34m,[0m [0my[0m[0;34m,[0m [0mi[0m[0;34m,[0m [0mj[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/PY/Gen/catalan_conjecture.py[0m in [0;36mcatalan1[0;34m(x, y, i, j)[0m
[1;32m     16[0m             [0;31m# print(f"Now the conjectures are {a} {b} {c} {d}")[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     17[0m             [0;32mif[0m [0ma[0m[0;34m**[0m[0;36m2[0m [0;34m-[0m [0mb[0m[0;34m**[0m[0;36m3[0m [0;34m==[0m [0;36m1[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 18[0;31m                 [0me[0m [0;34m=[0m [0mlist[0m[0;34m([0m[0ma[0m[0;34m,[0m [0mb[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     19[0m                 [0mprint[0m[0;34m([0m[0me[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     20[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: list expected at most 1 argument, got 2
